cors_origins: []
data_dir: ./data
debug: false
env: production
ffmpeg_path: C:\ffmpeg\bin\ffmpeg.exe
ffprobe_path: C:\ffmpeg\bin\ffprobe.exe
hw_accel: auto
max_transcode_jobs: 1
port: 8080
resource_limit: 5
transcode_preset: ultrafast
vaapi_device: /dev/dri/renderD128
web_dir: ./web/dist
