package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/nowen-video/nowen-video/internal/handler"
	"github.com/nowen-video/nowen-video/internal/middleware"
)

func registerAdminAPI(r *gin.Engine, handlers *handler.Handlers, jwtMiddleware gin.HandlerFunc) {
	r.OPTIONS("/api/admin/settings/douban/import", handler.DoubanImportCORS(), func(c *gin.Context) {
		c.Status(http.StatusNoContent)
	})
	r.POST("/api/admin/settings/douban/import", handler.DoubanImportCORS(), handlers.Admin.ImportDoubanCookie)

	admin := r.Group("/api/admin")
	admin.Use(jwtMiddleware, middleware.AdminOnly())

	admin.GET("/users", handlers.Admin.ListUsers)
	admin.POST("/users", handlers.Admin.CreateUser)
	admin.PUT("/users/:id", handlers.Admin.UpdateUser)
	admin.POST("/users/:id/disabled", handlers.Admin.SetUserDisabled)
	admin.DELETE("/users/:id", handlers.Admin.DeleteUser)
	admin.PUT("/users/:id/password", handlers.Admin.ResetUserPassword)
	admin.GET("/login-logs", handlers.Admin.ListLoginLogs)
	admin.GET("/audit-logs", handlers.Admin.ListAuditLogs)
	admin.GET("/invite-codes", handlers.Admin.ListInviteCodes)
	admin.POST("/invite-codes", handlers.Admin.CreateInviteCode)
	admin.DELETE("/invite-codes/:id", handlers.Admin.DeleteInviteCode)

	admin.GET("/system", handlers.Admin.SystemInfo)
	admin.GET("/transcode/status", handlers.Admin.TranscodeStatus)
	admin.GET("/transcode/throttle", handlers.Admin.TranscodeThrottleStats)
	admin.POST("/transcode/:taskId/cancel", handlers.Admin.CancelTranscode)
	admin.GET("/transcode-tasks", handlers.Admin.ListTranscodeTasks)
	admin.GET("/transcode-tasks/statistics", handlers.Admin.GetTranscodeStatistics)
	admin.POST("/transcode-tasks/batch-cancel", handlers.Admin.BatchCancelTranscodeTasks)
	admin.POST("/transcode-tasks/batch-delete", handlers.Admin.BatchDeleteTranscodeTasks)
	admin.POST("/transcode-tasks/batch-retry", handlers.Admin.BatchRetryTranscodeTasks)
	admin.POST("/transcode-tasks/batch-submit", handlers.Admin.BatchSubmitTranscodeTasks)
	admin.POST("/transcode-tasks/:id/cancel", handlers.Admin.CancelTranscodeTask)
	admin.POST("/transcode-tasks/:id/retry", handlers.Admin.RetryTranscodeTask)
	admin.DELETE("/transcode-tasks/:id", handlers.Admin.DeleteTranscodeTask)

	admin.GET("/settings/tmdb", handlers.Admin.GetTMDbConfig)
	admin.PUT("/settings/tmdb", handlers.Admin.UpdateTMDbConfig)
	admin.DELETE("/settings/tmdb", handlers.Admin.ClearTMDbConfig)
	admin.GET("/settings/tmdb/validate", handlers.Admin.ValidateTMDbConfig)
	admin.POST("/settings/tmdb/test", handlers.Admin.TestTMDbAPIKey)
	admin.PUT("/settings/tmdb/proxy", handlers.Admin.UpdateTMDbProxy)
	admin.DELETE("/settings/tmdb/proxy", handlers.Admin.ClearTMDbProxy)
	admin.POST("/settings/tmdb/proxy/test", handlers.Admin.TestTMDbProxy)
	admin.GET("/settings/system", handlers.Admin.GetSystemSettings)
	admin.PUT("/settings/system", handlers.Admin.UpdateSystemSettings)
	admin.GET("/strm/config", handlers.Admin.GetSTRMConfig)
	admin.PUT("/strm/config", handlers.Admin.UpdateSTRMConfig)

	admin.GET("/system-logs", handlers.SystemLog.ListSystemLogs)
	admin.GET("/system-logs/stats", handlers.SystemLog.GetSystemLogStats)
	admin.GET("/system-logs/export", handlers.SystemLog.ExportSystemLogs)
	admin.POST("/system-logs/clean", handlers.SystemLog.CleanSystemLogs)
	admin.POST("/batch/scan", handlers.Admin.BatchScan)
	admin.POST("/batch/scrape", handlers.Admin.BatchScrape)
	admin.GET("/permissions/:userId", handlers.Admin.GetUserPermission)
	admin.PUT("/permissions/:userId", handlers.Admin.UpdateUserPermission)
	admin.GET("/rating/:mediaId", handlers.Admin.GetContentRating)
	admin.PUT("/rating/:mediaId", handlers.Admin.SetContentRating)

	admin.GET("/metadata/search", handlers.Admin.SearchMetadata)
	admin.POST("/media/:mediaId/match", handlers.Admin.MatchMetadata)
	admin.POST("/media/:mediaId/unmatch", handlers.Admin.UnmatchMetadata)
	admin.PUT("/media/:mediaId/metadata", handlers.Admin.UpdateMediaMetadata)
	admin.DELETE("/media/:mediaId", handlers.Admin.DeleteMedia)
	admin.GET("/media/:mediaId/strm", handlers.Admin.GetMediaSTRM)
	admin.PUT("/media/:mediaId/strm", handlers.Admin.UpdateMediaSTRM)
	admin.POST("/series/:seriesId/match", handlers.Admin.MatchSeriesMetadata)
	admin.POST("/series/:seriesId/unmatch", handlers.Admin.UnmatchSeriesMetadata)
	admin.POST("/series/:seriesId/scrape", handlers.Admin.ScrapeSeriesMetadata)
	admin.PUT("/series/:seriesId/metadata", handlers.Admin.UpdateSeriesMetadata)
	admin.DELETE("/series/:seriesId", handlers.Admin.DeleteSeries)
	admin.POST("/series/merge", handlers.Admin.MergeSeries)
	admin.POST("/series/auto-merge", handlers.Admin.AutoMergeSeries)
	admin.GET("/series/merge-candidates", handlers.Admin.MergeCandidates)

	admin.GET("/images/tmdb", handlers.Admin.SearchTMDbImages)
	admin.POST("/media/:mediaId/image/upload", handlers.Admin.UploadMediaImage)
	admin.POST("/media/:mediaId/image/url", handlers.Admin.SetMediaImageByURL)
	admin.POST("/media/:mediaId/image/tmdb", handlers.Admin.SetMediaImageFromTMDb)
	admin.POST("/series/:seriesId/image/upload", handlers.Admin.UploadSeriesImage)
	admin.POST("/series/:seriesId/image/url", handlers.Admin.SetSeriesImageByURL)
	admin.POST("/series/:seriesId/image/tmdb", handlers.Admin.SetSeriesImageFromTMDb)
	admin.GET("/fs/browse", handlers.Admin.BrowseFS)

	admin.GET("/storage/webdav", handlers.Storage.GetWebDAVConfig)
	admin.PUT("/storage/webdav", handlers.Storage.UpdateWebDAVConfig)
	admin.POST("/storage/webdav/test", handlers.Storage.TestWebDAVConnection)
	admin.GET("/storage/webdav/status", handlers.Storage.GetWebDAVStatus)
	admin.POST("/storage/webdav/libraries/register", handlers.Storage.RegisterWebDAVLibrary)
	admin.GET("/storage/status", handlers.Storage.GetStorageStatus)
	admin.GET("/storage/alist", handlers.Storage.GetAlistConfig)
	admin.PUT("/storage/alist", handlers.Storage.UpdateAlistConfig)
	admin.POST("/storage/alist/test", handlers.Storage.TestAlistConnection)
	admin.GET("/storage/s3", handlers.Storage.GetS3Config)
	admin.PUT("/storage/s3", handlers.Storage.UpdateS3Config)
	admin.POST("/storage/s3/test", handlers.Storage.TestS3Connection)
	admin.POST("/system/clear-data", handlers.Admin.ClearAllData)

	admin.GET("/metadata/bangumi/search", handlers.Admin.SearchBangumi)
	admin.GET("/metadata/bangumi/subject/:subjectId", handlers.Admin.GetBangumiSubject)
	admin.POST("/media/:mediaId/match/bangumi", handlers.Admin.MatchMediaBangumi)
	admin.POST("/series/:seriesId/match/bangumi", handlers.Admin.MatchSeriesBangumi)
	admin.GET("/settings/bangumi", handlers.Admin.GetBangumiConfig)
	admin.PUT("/settings/bangumi", handlers.Admin.UpdateBangumiConfig)
	admin.DELETE("/settings/bangumi", handlers.Admin.ClearBangumiConfig)
	admin.GET("/metadata/douban/search", handlers.Admin.SearchDouban)
	admin.POST("/media/:mediaId/match/douban", handlers.Admin.MatchMediaDouban)
	admin.POST("/series/:seriesId/match/douban", handlers.Admin.MatchSeriesDouban)
	admin.GET("/settings/douban", handlers.Admin.GetDoubanConfig)
	admin.PUT("/settings/douban", handlers.Admin.UpdateDoubanConfig)
	admin.DELETE("/settings/douban", handlers.Admin.ClearDoubanConfig)
	admin.POST("/settings/douban/validate", handlers.Admin.ValidateDoubanConfig)
	admin.POST("/settings/douban/import-token", handlers.Admin.CreateDoubanImportToken)
	admin.GET("/settings/douban/import-token", handlers.Admin.GetDoubanImportTokenStatus)
	admin.GET("/metadata/thetvdb/search", handlers.Admin.SearchTheTVDB)
	admin.POST("/series/:seriesId/match/thetvdb", handlers.Admin.MatchSeriesTheTVDB)

	admin.GET("/ai/status", handlers.AI.GetAIStatus)
	admin.PUT("/ai/config", handlers.AI.UpdateAIConfig)
	admin.POST("/ai/auto-pilot", handlers.AI.EnableAutoPilot)
	admin.POST("/ai/test", handlers.AI.TestAIConnection)
	admin.DELETE("/ai/cache", handlers.AI.ClearAICache)
	admin.GET("/ai/cache", handlers.AI.GetAICacheStats)
	admin.GET("/ai/errors", handlers.AI.GetAIErrorLogs)
	admin.POST("/ai/test/search", handlers.AI.TestSmartSearch)
	admin.POST("/ai/test/recommend", handlers.AI.TestRecommendReason)
	admin.GET("/ai/models", handlers.AICost.ListModels)
	admin.GET("/ai/cost/estimate", handlers.AICost.Estimate)
	admin.GET("/ai/cost/summary", handlers.AICost.Summary)
	admin.GET("/ai/presets", handlers.AI.ListProviderPresets)
	admin.POST("/ai/quick-config/qwen", handlers.AI.QuickConfigQwen)
	admin.GET("/ai/router", handlers.AI.GetRouterSnapshot)
	admin.POST("/ai/router/switch", handlers.AI.ForceSwitchProvider)
	admin.POST("/ai/router/restore", handlers.AI.RestoreProvider)
	admin.GET("/ai/router/logs", handlers.AI.ListFailoverLogs)
	admin.GET("/ai/usage", handlers.AI.GetUsageBuckets)
	admin.GET("/stats/:userId", handlers.Stats.GetUserStatsAdmin)

	admin.POST("/scrape/tasks", handlers.ScrapeManager.CreateTask)
	admin.POST("/scrape/tasks/batch", handlers.ScrapeManager.BatchCreateTasks)
	admin.GET("/scrape/tasks", handlers.ScrapeManager.ListTasks)
	admin.GET("/scrape/tasks/:id", handlers.ScrapeManager.GetTask)
	admin.PUT("/scrape/tasks/:id", handlers.ScrapeManager.UpdateTask)
	admin.DELETE("/scrape/tasks/:id", handlers.ScrapeManager.DeleteTask)
	admin.POST("/scrape/tasks/:id/scrape", handlers.ScrapeManager.StartScrape)
	admin.POST("/scrape/tasks/:id/translate", handlers.ScrapeManager.TranslateTask)
	admin.POST("/scrape/batch/scrape", handlers.ScrapeManager.BatchStartScrape)
	admin.POST("/scrape/batch/translate", handlers.ScrapeManager.BatchTranslate)
	admin.POST("/scrape/batch/delete", handlers.ScrapeManager.BatchDeleteTasks)
	admin.POST("/scrape/export", handlers.ScrapeManager.ExportTasks)
	admin.GET("/scrape/statistics", handlers.ScrapeManager.GetStatistics)
	admin.GET("/scrape/history", handlers.ScrapeManager.GetHistory)

	admin.GET("/files", handlers.FileManager.ListFiles)
	admin.GET("/files/folders", handlers.FileManager.GetFolderTree)
	admin.GET("/files/by-folder", handlers.FileManager.ListFilesByFolder)
	admin.POST("/files/folders/create", handlers.FileManager.CreateFolder)
	admin.POST("/files/folders/rename", handlers.FileManager.RenameFolder)
	admin.POST("/files/folders/delete", handlers.FileManager.DeleteFolder)
	admin.GET("/files/:id", handlers.FileManager.GetFileDetail)
	admin.POST("/files/import", handlers.FileManager.ImportFile)
	admin.POST("/files/import/batch", handlers.FileManager.BatchImportFiles)
	admin.GET("/files/scan", handlers.FileManager.ScanDirectory)
	admin.PUT("/files/:id", handlers.FileManager.UpdateFile)
	admin.DELETE("/files/:id", handlers.FileManager.DeleteFile)
	admin.POST("/files/batch/delete", handlers.FileManager.BatchDeleteFiles)
	admin.POST("/files/:id/scrape", handlers.FileManager.ScrapeFile)
	admin.POST("/files/batch/scrape", handlers.FileManager.BatchScrapeFiles)
	admin.POST("/files/rename/preview", handlers.FileManager.PreviewRename)
	admin.POST("/files/rename/execute", handlers.FileManager.ExecuteRename)
	admin.POST("/files/rename/ai", handlers.FileManager.AIGenerateRenames)
	admin.GET("/files/rename/templates", handlers.FileManager.GetRenameTemplates)
	admin.GET("/files/stats", handlers.FileManager.GetStats)
	admin.GET("/files/logs", handlers.FileManager.GetOperationLogs)

	admin.POST("/batch/metadata/media", handlers.BatchMetadata.BatchUpdateMedia)
	admin.POST("/batch/metadata/series", handlers.BatchMetadata.BatchUpdateSeries)
	admin.POST("/import/test", handlers.BatchMetadata.TestImportConnection)
	admin.POST("/import/libraries", handlers.BatchMetadata.FetchImportLibraries)
	admin.POST("/import/external", handlers.BatchMetadata.ImportFromExternal)
	admin.GET("/export/library", handlers.BatchMetadata.ExportLibrary)
	admin.POST("/import/data", handlers.BatchMetadata.ImportFromExportData)

	admin.POST("/media/batch-move", handlers.Library.BatchMoveMedia)
	admin.GET("/duplicates", handlers.Library.DetectAllDuplicates)
	admin.GET("/libraries/:id/duplicates", handlers.Library.DetectDuplicates)
	admin.POST("/libraries/:id/mark-duplicates", handlers.Library.MarkDuplicates)

	admin.POST("/collections", handlers.Collection.CreateCollection)
	admin.POST("/collections/auto-match", handlers.Collection.AutoMatch)
	admin.POST("/collections/rematch", handlers.Collection.Rematch)
	admin.POST("/collections/merge-duplicates", handlers.Collection.MergeDuplicates)
	admin.POST("/collections/cleanup-empty", handlers.Collection.CleanupEmpty)
	admin.GET("/collections/duplicate-stats", handlers.Collection.DuplicateStats)
	admin.PUT("/collections/:id", handlers.Collection.UpdateCollection)
	admin.DELETE("/collections/:id", handlers.Collection.DeleteCollection)
	admin.POST("/collections/:id/media", handlers.Collection.AddMedia)
	admin.DELETE("/collections/:id/media/:mediaId", handlers.Collection.RemoveMedia)
}
