// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLibrary(arg1) {
  return window['go']['main']['App']['CreateLibrary'](arg1);
}

export function DeleteLibrary(arg1) {
  return window['go']['main']['App']['DeleteLibrary'](arg1);
}

export function DeleteMedia(arg1) {
  return window['go']['main']['App']['DeleteMedia'](arg1);
}

export function GetActorStats(arg1) {
  return window['go']['main']['App']['GetActorStats'](arg1);
}

export function GetDesktopSettings() {
  return window['go']['main']['App']['GetDesktopSettings']();
}

export function GetDirectoryStats(arg1) {
  return window['go']['main']['App']['GetDirectoryStats'](arg1);
}

export function GetGenreStats(arg1) {
  return window['go']['main']['App']['GetGenreStats'](arg1);
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetMediaDetail(arg1) {
  return window['go']['main']['App']['GetMediaDetail'](arg1);
}

export function GetMediaFiles(arg1) {
  return window['go']['main']['App']['GetMediaFiles'](arg1);
}

export function GetMediaList(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GetMediaList'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetMediaPreviews(arg1) {
  return window['go']['main']['App']['GetMediaPreviews'](arg1);
}

export function GetNFOEditorData(arg1) {
  return window['go']['main']['App']['GetNFOEditorData'](arg1);
}

export function GetSeriesStats(arg1) {
  return window['go']['main']['App']['GetSeriesStats'](arg1);
}

export function OpenMediaFolder(arg1) {
  return window['go']['main']['App']['OpenMediaFolder'](arg1);
}

export function OpenNFO(arg1) {
  return window['go']['main']['App']['OpenNFO'](arg1);
}

export function PlayFile(arg1) {
  return window['go']['main']['App']['PlayFile'](arg1);
}

export function PlayRandomLibraryMedia(arg1) {
  return window['go']['main']['App']['PlayRandomLibraryMedia'](arg1);
}

export function PlayWithExternalPlayer(arg1) {
  return window['go']['main']['App']['PlayWithExternalPlayer'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveNFOEditorData(arg1, arg2) {
  return window['go']['main']['App']['SaveNFOEditorData'](arg1, arg2);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function ScanLibraryWithMode(arg1, arg2) {
  return window['go']['main']['App']['ScanLibraryWithMode'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleWatched(arg1) {
  return window['go']['main']['App']['ToggleWatched'](arg1);
}

export function UpdateDesktopSettings(arg1) {
  return window['go']['main']['App']['UpdateDesktopSettings'](arg1);
}

export function UpdateLibrary(arg1) {
  return window['go']['main']['App']['UpdateLibrary'](arg1);
}
