// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {service} from '../models';

export function CreateLibrary(arg1:model.Library):Promise<void>;

export function DeleteLibrary(arg1:string):Promise<void>;

export function DeleteMedia(arg1:string):Promise<void>;

export function GetActorStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetDesktopSettings():Promise<main.DesktopSettings>;

export function GetDirectoryStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetGenreStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetLibraries():Promise<Array<model.Library>>;

export function GetMediaDetail(arg1:string):Promise<model.Media>;

export function GetMediaFiles(arg1:string):Promise<Array<string>>;

export function GetMediaList(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<any>;

export function GetMediaPreviews(arg1:string):Promise<Array<string>>;

export function GetNFOEditorData(arg1:string):Promise<service.NFOEditorData>;

export function GetSeriesStats(arg1:string):Promise<Array<main.StatsItem>>;

export function OpenMediaFolder(arg1:string):Promise<void>;

export function OpenNFO(arg1:string):Promise<void>;

export function PlayFile(arg1:string):Promise<void>;

export function PlayRandomLibraryMedia(arg1:string):Promise<string>;

export function PlayWithExternalPlayer(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function SaveNFOEditorData(arg1:string,arg2:service.NFOEditorData):Promise<void>;

export function ScanLibrary(arg1:string):Promise<void>;

export function ScanLibraryWithMode(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function ToggleWatched(arg1:string):Promise<void>;

export function UpdateDesktopSettings(arg1:main.DesktopSettings):Promise<void>;

export function UpdateLibrary(arg1:model.Library):Promise<void>;
